# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [1]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor(1)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(1)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [2]:
# TODO: Create a vector tensor
vector = torch.tensor([1, 2, 3, 4])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([1, 2, 3, 4])
Number of dimensions: 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [3]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[1,2,3], [4, 5, 6]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [9]:
# TODO: Create a 3D tensor
tensor_3d = torch.arange(1, 9).reshape(2, 2, 2)

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [10]:
# TODO: Create random tensor
random_tensor = torch.rand(4, 4)

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.0510, 0.5204, 0.5879, 0.8171],
        [0.3318, 0.2514, 0.0127, 0.3446],
        [0.0690, 0.6225, 0.3398, 0.8439],
        [0.0674, 0.9330, 0.9652, 0.8499]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [11]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(3, 224, 224)

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [13]:
# TODO: Create zeros tensor
zeros = torch.zeros(5, 6)

### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [17]:
random_tensor = torch.rand(3, 3)
# TODO: Create ones like
ones_like = torch.ones(random_tensor.shape)
random_tensor, ones_like

(tensor([[0.4176, 0.6368, 0.5628],
         [0.4653, 0.2406, 0.3393],
         [0.7671, 0.8445, 0.4970]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [19]:
# TODO: Create range tensor
range_tensor = torch.arange(0, 21, 2)
range_tensor

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [20]:
# TODO: float16 tensor
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# TODO: int64 tensor
int64_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.int64)

### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [21]:
# TODO: Change dtype
float32_tensor = float16_tensor.type(torch.float32)

## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [23]:
# TODO: Create tensor and print info
info_tensor = torch.rand(2, 3, 4)
info_tensor.shape, info_tensor.dtype, info_tensor.device

(torch.Size([2, 3, 4]), torch.float32, device(type='cpu'))

## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [24]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
tensor + 5

# TODO: Subtract 10
tensor - 10

# TODO: Multiply by 2
tensor * 2

# TODO: Divide by 10
tensor / 10

tensor([1., 2., 3.])

### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [27]:
# TODO: Create A and B
A = torch.rand(2, 3)
B = torch.rand(3, 2)

# TODO: Matrix mul using torch.mm
result_mm = torch.mm(A, B)

# TODO: Matrix mul using @
result_at = A @ B
assert result_mm.equal(result_at)

## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [29]:
agg_tensor = torch.arange(0, 101)
# TODO: Min
agg_tensor.min()
# TODO: Max
agg_tensor.max()
# TODO: Mean (note: may need to cast to float)
agg_tensor.type(torch.float32).mean()
# TODO: Sum
agg_tensor.sum()

tensor(5050)

### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [30]:
# TODO: Argmin
agg_tensor.argmin()
# TODO: Argmax
agg_tensor.argmax()

tensor(100)

## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [31]:
reshape_tensor = torch.arange(10)
# TODO: Reshape
reshaped = reshape_tensor.reshape(2, 5)

### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [32]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
# TODO: Stack vertically (dim=0)
torch.stack([tensor1, tensor2], dim=0)
# TODO: Stack horizontally (dim=1)
torch.stack([tensor1, tensor2], dim=1)

tensor([[[0.2669, 0.4532],
         [0.8486, 0.3866]],

        [[0.0417, 0.2767],
         [0.2184, 0.8587]]])

### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [34]:
squeeze_tensor = torch.rand(1, 3, 1)
# TODO: Squeeze
squeezed = squeeze_tensor.squeeze()

# TODO: Unsqueeze on dim=0
unsqueezed = squeeze_tensor.unsqueeze(dim=0)

### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [37]:
image_tensor = torch.rand(3, 100, 100)
# TODO: Permute
permuted = image_tensor.permute(1, 2, 0)
permuted

tensor([[[0.3450, 0.2602, 0.4274],
         [0.4429, 0.3473, 0.1471],
         [0.5126, 0.6212, 0.6784],
         ...,
         [0.7284, 0.4453, 0.7336],
         [0.3387, 0.4888, 0.0523],
         [0.8391, 0.9732, 0.1097]],

        [[0.5756, 0.4444, 0.0417],
         [0.4163, 0.1316, 0.6017],
         [0.1966, 0.4733, 0.4966],
         ...,
         [0.6828, 0.8947, 0.9885],
         [0.8759, 0.6699, 0.2278],
         [0.6136, 0.3192, 0.8825]],

        [[0.8359, 0.8755, 0.0170],
         [0.1486, 0.9138, 0.7001],
         [0.7906, 0.1189, 0.2203],
         ...,
         [0.4146, 0.2767, 0.1932],
         [0.8046, 0.1191, 0.1496],
         [0.7440, 0.5045, 0.2238]],

        ...,

        [[0.5930, 0.1898, 0.3412],
         [0.5911, 0.8704, 0.1229],
         [0.8999, 0.2119, 0.2657],
         ...,
         [0.2809, 0.2458, 0.1169],
         [0.8183, 0.0477, 0.3057],
         [0.7158, 0.7775, 0.3238]],

        [[0.5333, 0.8356, 0.9495],
         [0.1790, 0.1463, 0.0386],
         [0.

## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [41]:
index_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
# TODO: Get 5
print(index_tensor[0][1][1])
# TODO: Get second row [4,5,6]
index_tensor[0][1]

tensor(5)


tensor([4, 5, 6])

## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [42]:
import numpy as np
import torch
numpy_array = np.array([1,2,3,4])
# TODO: Convert to tensor
from_numpy = torch.from_numpy(numpy_array)

### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [44]:
pytorch_tensor = torch.tensor([5,6,7,8])
# TODO: Convert to NumPy
to_numpy = pytorch_tensor.numpy()

## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [45]:
# TODO: Set seed
torch.manual_seed(77)
rand1 = torch.rand(2,2)

# TODO: Reset seed for second tensor
torch.manual_seed(76)
rand2 = torch.rand(2,2)

# Check equality
print(rand1 == rand2)

tensor([[False, False],
        [False, False]])


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [47]:
# TODO: Set device
device = "mps"
import torch
torch.backends.mps.is_available()

True

### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [50]:
gpu_tensor = torch.tensor([10, 20, 30])
# TODO: Move to device
gpu_tensor = gpu_tensor.to("mps")

# TODO: Move back to CPU and to NumPy
cpu_numpy = gpu_tensor.cpu().numpy()